<a href="https://colab.research.google.com/github/omprateek-non/NLP.assignments/blob/main/assignment_lecture4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Use the following dataset - https://www.kaggle.com/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [1]:
import pandas as pd
import numpy as np
df= pd.read_csv("IMDB Dataset.csv")

In [2]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [4]:
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer

nltk.download("stopwords", quiet=True)
nltk.download("wordnet", quiet=True)
nltk.download("omw-1.4", quiet=True)

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()

def clean_text(text):

    text = str(text).lower()

    # Remove HTML
    text = re.sub(r'<.*?>', ' ', text)

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove numbers and special characters
    text = re.sub(r'[^a-z\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    # Tokenize and remove stopwords
    words = [word for word in text.split() if word not in stop_words]

    # Lemmatization
    words = [lemmatizer.lemmatize(word) for word in words]

    # Stemming
    words = [stemmer.stem(word) for word in words]

    return " ".join(words)

df['review'] = df['review'].apply(clean_text)

In [5]:
# Get all words from all reviews using basic Python
all_words = []
for review in df['review']:
    all_words.extend(review.split())

# Calculate total number of words
total_words = len(all_words)

# Calculate total number of unique words (vocabulary)
vocabulary = set(all_words)
total_unique_words = len(vocabulary)

print(f"Total number of words in the corpus: {total_words}")
print(f"Total number of unique words (vocabulary): {total_unique_words}")

Total number of words in the corpus: 5951375
Total number of unique words (vocabulary): 122668

In [6]:
# Problem 4

# Apply bag words and find the vocabulary also find the times each word has occured
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the text data
X = vectorizer.fit_transform(df['review'])
df

                                                  review sentiment
0      one review mention watch oz episod youll hook ...  positive
1      wonder littl product film techniqu unassum old...  positive
2      thought wonder way spend time hot summer weeke...  positive
3      basic there famili littl boy jake think there ...  negative
4      petter mattei love time money visual stun film...  positive
...                                                  ...       ...
49995  thought movi right good job wasnt creativ orig...  positive
49996  bad plot bad dialogu bad act idiot direct anno...  negative
49997  cathol taught parochi elementari school nun ta...  negative
49998  im go disagre previou comment side maltin one ...  negative
49999  one expect star trek movi high art fan expect ...  negative

[50000 rows x 2 columns]

In [7]:
vectorizer = CountVectorizer(
    max_features=10000,
    stop_words='english',
    ngram_range=(1,2)
)
df

                                                  review sentiment
0      one review mention watch oz episod youll hook ...  positive
1      wonder littl product film techniqu unassum old...  positive
2      thought wonder way spend time hot summer weeke...  positive
3      basic there famili littl boy jake think there ...  negative
4      petter mattei love time money visual stun film...  positive
...                                                  ...       ...
49995  thought movi right good job wasnt creativ orig...  positive
49996  bad plot bad dialogu bad act idiot direct anno...  negative
49997  cathol taught parochi elementari school nun ta...  negative
49998  im go disagre previou comment side maltin one ...  negative
49999  one expect star trek movi high art fan expect ...  negative

[50000 rows x 2 columns]

In [8]:
# Problem 5

# Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary
# Model 1
CountVectorizer(
    max_features=10000,
    ngram_range=(1,1)
)

# Model 2
CountVectorizer(
    max_features=10000,
    ngram_range=(1,2)
)

# Model 3
CountVectorizer(
    max_features=10000,
    ngram_range=(2,2)
)

# Model 4
CountVectorizer(
    max_features=10000,
    ngram_range=(1,3)
)

CountVectorizer(max_features=10000, ngram_range=(1, 3))

In [10]:
# Problem 6

# Apply tf-idf and find out the idf scores of words, also find out the vocabulary.
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

vectorizer = CountVectorizer(
    max_features=10000,
    stop_words='english',
    min_df=5,
    max_df=0.8,
    ngram_range=(1,2)
)

X = vectorizer.fit_transform(df['review'])

print("Vocabulary Size:", len(vectorizer.get_feature_names_out()))

feature_names = vectorizer.get_feature_names_out()

bow_df = pd.DataFrame(
    X[:5].toarray(),
    columns=feature_names
)

display(bow_df)

Vocabulary Size: 10000

,aaron,abandon,abbott,abc,abduct,abil,abl,abl make,aboard,abomin,...,zealand,zellweg,zero,zizek,zoey,zombi,zombi film,zombi movi,zone,zoom
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

tfidf = TfidfVectorizer(
    max_features=10000,
    stop_words='english',
    min_df=5,
    max_df=0.8,
    ngram_range=(1,2)
)

X = tfidf.fit_transform(df['review'])

print("Vocabulary Size:", len(tfidf.get_feature_names_out()))

feature_names = tfidf.get_feature_names_out()

tfidf_df = pd.DataFrame(
    X[:5].toarray(),
    columns=feature_names
)

display(tfidf_df)

Vocabulary Size: 10000

,aaron,abandon,abbott,abc,abduct,abil,abl,abl make,aboard,abomin,...,zealand,zellweg,zero,zizek,zoey,zombi,zombi film,zombi movi,zone,zoom
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.207219,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0